### PR TITLE
OOP school library: refactor your code

### PR DESCRIPTION
**Pull request by PrantoshB**
## Hello There 👋

hello

In this branch, I and my coding partner Gaurav have:
- Extracted some pieces of logic into separate class
- Refactored `main.rb` file
- Fixed Linters Errors
- Followed Git and GitHub Flows

### Thanks 🍻
Prantosh

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Prantosh & Gaurav, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🏃 🏃‍♂️  

## Highlights 👍  
- Good job implementing clean code principles so far!
- ReadMe looks professional!

## Required Changes ♻️
- [ ]  Nice job, your code is taking shape 👌 , However, we can further improve upon our _create_ and _list_all methods found in the `app.rb`, which at present do not adhere to the single responsibility rule. Let's ensure that *all* requests for input and input validation are placed in the `main.rb`, file or in classes or methods whose responsibilities are to request or validate input,  for instance `get.chomps` or _switch statements_ should be handled in different class/ methods. We can then reference those values which were stored in objects during the request in our `create` or `list` methods. The affected methods in the `app.rb` to consider for further refactoring includes:
  * `create_person` 
  * `craete_teacher`
  * `create_rental` and
  * `list_rentals`

I urge you to kindly read further on the same via [this link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello @PrantoshB  and @gauravgangwarweb   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have inspected your project and checked what was requested by the previous reviewer (@rloterh ). What the reviewer means when he says that our project still does not adhere to the single responsibility rule is that eg the function of the "Create_person" should be stripped down to only include the functionality for exactly "Creating the person (student or teacher) and the functionality for asking for the details from the user should be in another method.


Just as an example, For creating and listing people, you could have the following methods broken down which ensure that a method does exactly one thing:

```
def display_people
    @people.each_with_index do |p, index|
      puts "#{index + 1} [Student] | ID: #{p.id} - Name: #{p.name} - Age: #{p.age}" if p.is_a?(Student)
      puts "#{index + 1} [Teacher] | ID: #{p.id} - Name: #{p.name} - Age: #{p.age}" if p.is_a?(Teacher)
    end
  end

def list_people
    if @people.length.zero?
      (puts 'People list is empty')
    else
      puts 'People list:'
      display_people
    end
  end

def create_student(name, age)
    puts 'Has parent permission? [Y/N]'
    permission = gets.chomp.downcase
    permission = true if permission == 'y'
    permission = false if permission == 'n'
    puts 'Classroom:'
    classroom = gets.chomp
    student = Student.new(age, classroom, name, parent_permission: permission)
    puts "Student #{student.name} has been created successfully."
  end

  def create_teacher(name, age)
    puts 'Specialization:'
    specialization = gets.chomp
    teacher = Teacher.new(age, specialization, name)
    puts "Teacher #{teacher.name} has been created successfully."
  end

  def create_person
    option = ''
    loop do
      puts "Do you want to create a student (1) or a teacher (2)? [Input the number]\n"
      option = gets.chomp.to_i
      break if [1, 2].include?(option)
    end
    puts 'Name:'
    name = gets.chomp
    puts 'Age:'
    age = gets.chomp.to_i
    case option
    when 1
      create_student(name, age)
    when 2
      create_teacher(name, age)
    end
  end
```

I hope now with this explanation, the requested changes are now clear to you and you will be able to make the requested changes. Have fun implementing SOLID to your project! :partying_face: 



In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Review by franclobo — APPROVED** [review]
Hi @PrantoshB, 

# STATUS: APPROVED 😄 

git-merge

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✔️ 
- descriptive PR ✔️ 
- The app works as expected ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Thanks @franclobo for reviewing our project.
Have a good day 💐

**Pull request merged**
